#!/bin/sh
#
# N3DS_RESOLVCONF: publish the DHCP nameservers to BOTH of this device's
# resolvers.
#
# There are two, and they read different things:
#
#   * bionic -- everything written in Java, and every Android native library --
#     reads the net.dns1..net.dns4 system properties and never opens a file.
#   * musl reads /etc/resolv.conf and nothing else.  It has no idea Android
#     properties exist.  /system/bin/telco_https, the certificate-verifying
#     HTTPS transport the Phone app shells out to for 3DSTelco, is statically
#     linked against musl, so /etc/resolv.conf is the only thing in this image
#     standing between the dialer and "Could not resolve host".
#
# Neither was reliably written.  android_udhcpc.sh set only the dhcp.<iface>.*
# properties that Android 2.0's libnetutils waits on -- never net.dns* -- and
# /etc/resolv.conf was left entirely to Buildroot's stock default.script, which
# writes it through a mktemp temporary in /tmp.  /etc is also excluded from the
# SD image by sync_android_to_sdcard.sh, so when that write does not happen
# there is no file at all, and musl with no resolv.conf queries 127.0.0.1,
# where nothing on this device is listening.  That failure never leaves the
# handheld, which is why the server sees no request and logs no error.
#
# Usage: android_resolvconf.sh <interface> [nameserver ...]
# With no nameservers on the command line they are read back from the
# dhcp.<iface>.* properties, so this is also callable from an init property
# trigger or by hand over adb after any DHCP path.

INTERFACE=${1:-wlan0}
shift 2>/dev/null
SETPROP=${SETPROP:-/system/bin/setprop}
GETPROP=${GETPROP:-/system/bin/getprop}
RESOLV_CONF=${RESOLV_CONF:-/etc/resolv.conf}

log() {
	echo "resolvconf: $1" > /dev/kmsg 2>/dev/null
}

valid() {
	# 0.0.0.0 is how android_udhcpc.sh spells "the lease did not carry one".
	case "$1" in
		""|0.0.0.0|255.255.255.255) return 1 ;;
	esac
	# Dotted quad only; musl would reject anything else anyway.
	echo "$1" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'
}

SERVERS=
for candidate in "$@"; do
	valid "$candidate" && SERVERS="$SERVERS $candidate"
done

if [ -z "$SERVERS" ] && [ -x "$GETPROP" ]; then
	for prop in dns1 dns2; do
		candidate=$("$GETPROP" "dhcp.$INTERFACE.$prop" 2>/dev/null)
		valid "$candidate" && SERVERS="$SERVERS $candidate"
	done
fi

# Last resort: the default gateway.  On every consumer router this handheld is
# ever going to meet, the gateway is also a DNS forwarder, and a lease that
# carries a router but no DNS option is a misconfigured network rather than a
# network with no resolver.  Keeping the query on the user's own LAN is the
# point -- this deliberately does not reach for a public resolver.
if [ -z "$SERVERS" ] && [ -x "$GETPROP" ]; then
	candidate=$("$GETPROP" "dhcp.$INTERFACE.gateway" 2>/dev/null)
	if valid "$candidate"; then
		SERVERS=" $candidate"
		log "lease carried no DNS; falling back to the gateway $candidate"
	fi
fi

if [ -z "$SERVERS" ]; then
	log "no usable nameserver for $INTERFACE; leaving $RESOLV_CONF alone"
	exit 0
fi

# One truncating redirect, no temporary file.  Buildroot's default.script
# stages through mktemp in /tmp, which on this board is the 82 KB initramfs
# root; if /tmp is missing or full the stock script silently writes nothing.
# The payload here is about a hundred bytes and musl opens the file exactly
# once per lookup, so a direct write is both simpler and strictly safer than
# a staging step that can fail on its own.
{
	echo "# generated by /etc/android_resolvconf.sh for $INTERFACE"
	for server in $SERVERS; do
		echo "nameserver $server"
	done
	# musl budgets the whole lookup across all listed servers; two servers
	# at two seconds each keeps a dead first nameserver from eating
	# telco_https' 15 s connect timeout on its own.
	echo "options timeout:2 attempts:2"
} > "$RESOLV_CONF" 2>/dev/null

if [ -s "$RESOLV_CONF" ]; then
	log "$RESOLV_CONF ->$SERVERS"
else
	log "FAILED to write $RESOLV_CONF; musl name resolution will not work"
fi

# The bionic half.  ConnectivityService copies net.<iface>.dns* into net.dns*
# once it notices a connected network, but it only notices networks it brought
# up itself; write both so a lease taken by any path reaches the Java resolver.
if [ -x "$SETPROP" ]; then
	index=1
	for server in $SERVERS; do
		"$SETPROP" "net.$INTERFACE.dns$index" "$server"
		"$SETPROP" "net.dns$index" "$server"
		index=$((index + 1))
	done
fi

exit 0
