#!/bin/bash
# libbionic_compat.a -- functions GCC assumes libc provides but bionic does not.
#
# Right now that is just sincos()/sincosf(). GCC's cse_sincos pass rewrites an
# adjacent sin(x)/cos(x) pair on the same argument into one sincos() call, and
# it decides whether that is legal from the *toolchain's* libc, which here is
# the glibc-targeting arm-buildroot-linux-gnueabihf compiler. glibc has
# sincos; bionic's libm does not, so linking against bionic then fails with
# undefined references. ICU's i18n/astro.cpp (CalendarAstronomer) triggers it.
#
# -fno-builtin-sincos does NOT prevent this: that flag stops GCC treating a
# *call to* sincos specially, but the optimisation pass still synthesises the
# call. Supplying the function is the reliable fix, and it is what a bionic
# with this gap filled would do anyway.
. "$(dirname "${BASH_SOURCE[0]:-$0}")/a3ds_env.sh"
set -e

TC="${ANDROID3DS_ROOT}"/toolchain/armv6-eabihf--glibc--stable-2025.08-1/bin
GCC="$TC/arm-buildroot-linux-gnueabihf-gcc"
AR="$TC/arm-buildroot-linux-gnueabihf-ar"

BIONIC="${ANDROID3DS_ROOT}"/third_party/bionic
OUT="${ANDROID3DS_ROOT}"/build/bionic_compat
mkdir -p "$OUT/obj"

cat > "$OUT/sincos.c" <<'EOF'
/* Generated by build_bionic_compat.sh -- see that script for why. */
#include <math.h>

/* -fno-builtin on this file so GCC cannot "optimise" these definitions into
 * self-recursive calls to themselves. */
void sincos(double x, double *s, double *c)
{
    *s = sin(x);
    *c = cos(x);
}

void sincosf(float x, float *s, float *c)
{
    *s = sinf(x);
    *c = cosf(x);
}

void sincosl(long double x, long double *s, long double *c)
{
    *s = (long double) sin((double) x);
    *c = (long double) cos((double) x);
}
EOF

"$GCC" -nostdinc -O2 -std=gnu89 -fgnu89-inline -fno-pic -fno-stack-protector \
    -fno-builtin \
    -D__ARM_EABI__ -DANDROID \
    -isystem "$($GCC -print-file-name=include)" \
    -I "$BIONIC/libc/include" \
    -I "$BIONIC/libm/include" \
    -I "$BIONIC/libc/kernel/common" \
    -I "$BIONIC/libc/kernel/arch-arm" \
    -I "$BIONIC/libc/arch-arm/include" \
    -c "$OUT/sincos.c" -o "$OUT/obj/sincos.o"

rm -f "$OUT/libbionic_compat.a"
"$AR" rcs "$OUT/libbionic_compat.a" "$OUT/obj/sincos.o"
ls -la "$OUT/libbionic_compat.a"
"$TC/arm-buildroot-linux-gnueabihf-nm" "$OUT/libbionic_compat.a" | grep -E " T sincos"

# Regression guard: GCC's cse_sincos pass must not turn either wrapper back
# into a call to itself.  In a relocatable object that mistake appears as a
# branch relocation from the function to the same symbol.
if "$TC/arm-buildroot-linux-gnueabihf-objdump" -dr "$OUT/obj/sincos.o" \
    | grep -E 'R_ARM_(CALL|JUMP24)[[:space:]]+sincos(f|l)?$'; then
    echo "ERROR: a sincos compatibility wrapper became self-recursive" >&2
    exit 1
fi
