#!/bin/bash
# Build libexpat.a and libsqlite.a for the target.
#
# libcore needs both:
#   expat  -> xml/src/main/native/org_apache_harmony_xml_ExpatParser.cpp
#   sqlite -> sql/src/main/native/{sqlite_jni.c,...} (SQLite.Database etc)
#
# Source lists and -D flags are taken from each project's own AOSP Android.mk
# so the build matches what Eclair's libcore was written against.
. "$(dirname "${BASH_SOURCE[0]:-$0}")/a3ds_env.sh"
set -e

TC="${ANDROID3DS_ROOT}"/toolchain/armv6-eabihf--glibc--stable-2025.08-1/bin
GCC="$TC/arm-buildroot-linux-gnueabihf-gcc"
GXX="$TC/arm-buildroot-linux-gnueabihf-g++"
AR="$TC/arm-buildroot-linux-gnueabihf-ar"

TP="${ANDROID3DS_ROOT}"/third_party
BIONIC=$TP/bionic
SYSCORE=$TP/system_core
BUILD="${ANDROID3DS_ROOT}"/build

# -std=gnu89 -fgnu89-inline: bionic's ctype.h uses gnu89 inline semantics for
# isalnum/isalpha/..., so building under the default gnu17 emits an external
# definition of each in every TU and libsqlite.a then collides with
# libcrypto.a at link time. See build_openssl.sh.
BASE_CFLAGS="-nostdinc -O2 -fno-stack-protector -fno-pic -std=gnu89 -fgnu89-inline \
-Wno-implicit-function-declaration -Wno-attributes -Wno-pointer-sign \
-D__ARM_EABI__ -DANDROID -DHAVE_ARM_TLS_REGISTER \
-isystem $($GCC -print-file-name=include) \
-I $BIONIC/libc/include \
-I $BIONIC/libm/include \
-I $BIONIC/libc/kernel/common \
-I $BIONIC/libc/kernel/arch-arm \
-I $BIONIC/libc/arch-arm/include \
-I $SYSCORE/include \
-I $TP/frameworks/base/include"

# ---------------------------------------------------------------- expat ----
EXPAT=$TP/expat
OUT=$BUILD/expat
mkdir -p "$OUT/obj"; rm -f "$OUT"/obj/*.o

# HAVE_EXPAT_CONFIG_H makes expat.h pick up expat_config.h, which is checked
# in (generated by AOSP's configure run), so no autoconf pass is needed.
EXPAT_CFLAGS="$BASE_CFLAGS -DHAVE_EXPAT_CONFIG_H -I $EXPAT -I $EXPAT/lib"

echo "=== expat ==="
for f in xmlparse.c xmlrole.c xmltok.c; do
    echo "  CC lib/$f"
    "$GCC" $EXPAT_CFLAGS -c "$EXPAT/lib/$f" -o "$OUT/obj/${f%.c}.o"
done
rm -f "$OUT/libexpat.a"
"$AR" rcs "$OUT/libexpat.a" "$OUT"/obj/*.o
ls -la "$OUT/libexpat.a"

# --------------------------------------------------------------- sqlite ----
SQLITE=$TP/sqlite/dist
OUT=$BUILD/sqlite
mkdir -p "$OUT/obj"; rm -f "$OUT"/obj/*.o

# Flags straight from external/sqlite/dist/Android.mk. SQLITE_THREADSAFE=1
# matters: Dalvik is heavily multithreaded.
SQLITE_CFLAGS="$BASE_CFLAGS \
-DHAVE_USLEEP=1 \
-DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 \
-DSQLITE_THREADSAFE=1 \
-DNDEBUG=1 \
-DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 \
-DSQLITE_DEFAULT_AUTOVACUUM=1 \
-DSQLITE_TEMP_STORE=3 \
-DSQLITE_ENABLE_FTS3 \
-DSQLITE_ENABLE_FTS3_BACKWARDS \
-I $SQLITE -I $SYSCORE/include/cutils"

echo "=== sqlite ==="
echo "  CC sqlite3.c (amalgamation)"
"$GCC" $SQLITE_CFLAGS -c "$SQLITE/sqlite3.c" -o "$OUT/obj/sqlite3.o"
rm -f "$OUT/libsqlite.a"
"$AR" rcs "$OUT/libsqlite.a" "$OUT"/obj/*.o
ls -la "$OUT/libsqlite.a"

# ------------------------------------------------------- sqlite3_android ----
# register_android_functions()/register_localized_collators() -- the ICU-
# backed collation/phone-number-normalization additions
# android_database_SQLiteDatabase.cpp calls. A separate directory from the
# amalgamation, hence its own libsqlite3_android.a.
SQLA=$TP/sqlite/android
OUT=$BUILD/sqlite3_android
mkdir -p "$OUT/obj"; rm -f "$OUT"/obj/*.o

SQLA_CXXFLAGS="-nostdinc++ -nostdinc -std=gnu++98 -fno-exceptions -fno-rtti \
-fno-stack-protector -fno-pic -O2 -fno-delete-null-pointer-checks \
-Wno-attributes -Wno-invalid-offsetof -Wno-write-strings \
-D__ARM_EABI__ -DANDROID -DHAVE_ARM_TLS_REGISTER \
-include $SYSCORE/include/arch/linux-arm/AndroidConfig.h \
-isystem $($GXX -print-file-name=include) \
-I $BIONIC/libstdc++/include \
-I $BIONIC/libc/include \
-I $BIONIC/libm/include \
-I $BIONIC/libc/kernel/common \
-I $BIONIC/libc/kernel/arch-arm \
-I $BIONIC/libc/arch-arm/include \
-I $SYSCORE/include \
-I $TP/frameworks/base/include \
-I $SQLITE \
-I $SQLA \
-I $TP/icu4c/common \
-I $TP/icu4c/i18n"

echo "=== sqlite3_android ==="
for f in sqlite3_android.cpp PhoneNumberUtils.cpp PhoneticStringUtils.cpp; do
    echo "  CXX android/$f"
    "$GXX" $SQLA_CXXFLAGS -c "$SQLA/$f" -o "$OUT/obj/${f%.cpp}.o"
done
rm -f "$OUT/libsqlite3_android.a"
"$AR" rcs "$OUT/libsqlite3_android.a" "$OUT"/obj/*.o
ls -la "$OUT/libsqlite3_android.a"

echo
echo "all built"
