#!/bin/bash
# Build libicuuc.a, libicui18n.a and libicudata.a for the target.
#
# ICU is the last and largest of libcore's external dependencies, and it is not
# optional: java.lang.Character, String case mapping and java.util.Locale all
# route into the com.ibm.icu4jni.* natives, which are thin wrappers over ICU.
#
# Source lists, -D flags and include paths are taken from icu4c's own
# common/Android.mk and i18n/Android.mk. This is ICU 3.8 (icudt38), the version
# Eclair shipped -- the checked-in unicode/platform.h is already generated for
# it, so no configure pass is needed.
#
# The data: AOSP compiles a prebuilt .dat blob into a shared library by running
# a host tool that emits an assembly file exporting `icudt38_dat`. We do the
# same thing with a three-line .S using .incbin, which is exactly what that
# tool generates. Alignment matters -- ICU casts the blob to structs, so it
# must be at least 16-byte aligned.
. "$(dirname "${BASH_SOURCE[0]:-$0}")/a3ds_env.sh"
set -e

TC="${ANDROID3DS_ROOT}"/toolchain/armv6-eabihf--glibc--stable-2025.08-1/bin
GCC="$TC/arm-buildroot-linux-gnueabihf-gcc"
GXX="$TC/arm-buildroot-linux-gnueabihf-g++"
AR="$TC/arm-buildroot-linux-gnueabihf-ar"

TP="${ANDROID3DS_ROOT}"/third_party
BIONIC=$TP/bionic
LSTL=$BIONIC/libstdc++
SYSCORE=$TP/system_core
ICU=$TP/icu4c
OUT="${ANDROID3DS_ROOT}"/build/icu4c

# Which locale set to link in. "us" is the smallest (EN + ES, 1.6 MB);
# swap for icudt38l-default.dat (CS/DE/EN/ES/FR/NL) or -large.dat as needed.
ICU_DATA=${ICU_DATA:-$ICU/stubdata/icudt38l-us.dat}

mkdir -p "$OUT/obj/common" "$OUT/obj/i18n" "$OUT/gen"
rm -f "$OUT"/obj/common/*.o "$OUT"/obj/i18n/*.o

extract_srcs() {
python3 - "$1" <<'PYEOF'
import re, sys
text = open(sys.argv[1]).read()
# There is more than one LOCAL_SRC_FILES block per file: i18n/Android.mk has a
# ":=" block with five .c files and then a separate "+=" block with ~130 .cpp
# files. Collect every block, not just the first.
files = []
for m in re.finditer(r"LOCAL_SRC_FILES\s*[:+]?=(.*?)(?=\n[A-Za-z_]|\n\s*\n|\Z)",
                     text, flags=re.S):
    block = m.group(1).replace("\\\n", " ")
    for tok in block.split():
        if tok.endswith(".c") or tok.endswith(".cpp"):
            files.append(tok)
if not files:
    sys.exit("no LOCAL_SRC_FILES in " + sys.argv[1])
seen = set()
for f in files:
    if f not in seen:
        seen.add(f)
        print(f)
PYEOF
}

# U_STATIC_IMPLEMENTATION: we link ICU statically, so its U_EXPORT/U_IMPORT
# decorations must resolve to nothing rather than dllimport-style visibility.
# -fno-builtin-sincos: GCC rewrites an adjacent sin(x)/cos(x) pair into a
# single sincos() call (i18n/astro.cpp does exactly that). glibc has sincos;
# bionic's libm does not, so the optimisation produces an undefined reference.
COMMON_FLAGS="-nostdinc -O2 -fno-delete-null-pointer-checks -fno-stack-protector -fno-pic -fno-builtin-sincos \
-D_REENTRANT -DARM_FLAG -DU_STATIC_IMPLEMENTATION \
-Wno-attributes -Wno-implicit-function-declaration \
-D__ARM_EABI__ -DANDROID -DHAVE_ARM_TLS_REGISTER \
-isystem $($GCC -print-file-name=include) \
-I $BIONIC/libc/include \
-I $BIONIC/libm/include \
-I $BIONIC/libc/kernel/common \
-I $BIONIC/libc/kernel/arch-arm \
-I $BIONIC/libc/arch-arm/include \
-I $SYSCORE/include \
-I $ICU/common \
-I $ICU/i18n"

CXX_EXTRA="-nostdinc++ -std=gnu++98 -fno-exceptions -fno-rtti \
-Wno-invalid-offsetof -I $LSTL/include"

build_dir() {
    local dir="$1" impl="$2" name="$3"
    local srcs; srcs=$(extract_srcs "$ICU/$dir/Android.mk")
    local n=0 ok=0 fail=0 failed=""
    for f in $srcs; do
        n=$((n+1))
        local o="$OUT/obj/$dir/${f%.*}.o"
        local cc="$GCC" extra=""
        case "$f" in *.cpp) cc="$GXX"; extra="$CXX_EXTRA" ;; esac
        if "$cc" $COMMON_FLAGS -D$impl $extra -c "$ICU/$dir/$f" -o "$o" \
                > "$o.log" 2>&1; then
            ok=$((ok+1))
        else
            fail=$((fail+1)); failed="$failed $f"
        fi
    done
    echo "$name: total=$n OK=$ok FAIL=$fail"
    if [ -n "$failed" ]; then
        echo "  failed:$failed"
        for f in $failed; do
            echo "--- $f"
            grep -m3 -E "error:|fatal error:" "$OUT/obj/$dir/${f%.*}.o.log" || \
                head -5 "$OUT/obj/$dir/${f%.*}.o.log"
        done
        return 1
    fi
    rm -f "$OUT/lib$name.a"
    "$AR" rcs "$OUT/lib$name.a" "$OUT"/obj/$dir/*.o
    ls -la "$OUT/lib$name.a"
}

echo "=== libicuuc (common) ==="
build_dir common U_COMMON_IMPLEMENTATION icuuc
echo
echo "=== libicui18n (i18n) ==="
build_dir i18n U_I18N_IMPLEMENTATION icui18n

echo
echo "=== libicudata ($(basename "$ICU_DATA")) ==="
cat > "$OUT/gen/icudata.S" <<EOF
/* Generated by build_icu4c.sh -- equivalent to what AOSP's genccode host tool
 * emits for stubdata. ICU looks the blob up by this symbol name
 * (U_ICUDATA_ENTRY_POINT). */
    .globl icudt38_dat
    .section .rodata
    .balign 16
icudt38_dat:
    .incbin "$ICU_DATA"
EOF
"$GCC" -c "$OUT/gen/icudata.S" -o "$OUT/obj/icudata.o"
rm -f "$OUT/libicudata.a"
"$AR" rcs "$OUT/libicudata.a" "$OUT/obj/icudata.o"
ls -la "$OUT/libicudata.a"
"$TC/arm-buildroot-linux-gnueabihf-nm" "$OUT/libicudata.a" | grep icudt38_dat
