#!/bin/bash
# Pre-bake a /system/app side-by-side odex under qemu-arm-static, so the
# device does zero on-device dexopt for the selected system APK.
#
# Why a side-by-side .odex and not a dalvik-cache entry:
#   - installd's dexopt() (frameworks/base/cmds/installd/commands.c) returns
#     immediately if the sibling <apk>.odex exists -- PackageManager never even
#     opens a dalvik-cache file for the app, so there is no /data write at all.
#   - dvmJarFileOpen() (dalvik/vm/JarFile.c) also prefers the side-by-side
#     .odex over the classes.dex-in-apk + dalvik-cache path.
#   - The dependency check for a side-by-side odex runs with sourceAvail=false
#     (dvmCheckOptHeaderAndDependencies), so modWhen/CRC of the APK are NOT
#     compared -- only the VM build number and the bootclasspath cache names +
#     dex signatures must match. Those are constant per build, which makes this
#     robust against APK rebuilds as long as the bootclasspath jars don't move.
#
# The odex is generated by the REAL ARM dexopt under qemu, so the dependency
# section is written from the actual bootclasspath jars + pre-baked dalvik-cache
# (the ones build_dexpreopt_qemu.sh produced). The signature recorded for each
# bootclasspath entry is the SHA-1 of the *loaded* dex (from dalvik-cache), so
# this MUST be run against the same bootclasspath + dalvik-cache as deployed.
# Run build_dexpreopt_qemu.sh first (it builds dexopt_qemu + the cache), then
# this script.
#
# Re-run whenever Launcher2.apk content changes AND build_dexpreopt_qemu.sh
# produced a new dalvik-cache (i.e. bootclasspath jars changed). Because the
# side-by-side check skips modWhen/crc, a stale Launcher2.odex from an OLD apk
# would still be accepted -- so always regenerate this together with the apk.
. "$(dirname "${BASH_SOURCE[0]:-$0}")/a3ds_env.sh"
set -e

APK_NAME="${APK_NAME:-Launcher2}"

BUILD="${ANDROID3DS_ROOT}"/build
QEMU="${ANDROID3DS_ROOT}"/toolchain/qemu/qemu-arm-static
FAKEROOT=$BUILD/dexpreopt_fakeroot
SD="${ANDROID3DS_WIN}"/sdcard/linux/android
OVERLAY="${ANDROID3DS_ROOT}"/third_party/buildroot/board/nintendo3ds/rootfs_overlay

# N3DS_PREBAKE_WSL_TARGET: also deploy to the canonical WSL staging tree.
# verify_release_artifacts.sh reads whichever tree it is launched from, and
# sync_android_to_sdcard.sh has to run BEFORE dexpreopt and prebake -- so
# without this copy the WSL tree keeps the previous build's odex and the gate
# reports STALE for a file that was just rebuilt.
WSL_SD="${ANDROID3DS_ROOT}"/sdcard/linux/android

[ -x "$BUILD/dexopt/dexopt_qemu" ] || { echo "missing dexopt_qemu -- run build_dexpreopt_qemu.sh first"; exit 1; }
[ -f "$FAKEROOT/data/dalvik-cache/system@framework@core.jar@classes.dex" ] || {
    echo "missing fakeroot dalvik-cache -- run build_dexpreopt_qemu.sh first"; exit 1; }

echo "=== 1. stage $APK_NAME.apk + tools into fakeroot ==="
# Bake from the overlay (source of truth for a freshly built APK), not the SD
# staging copy -- if the APK was just rebuilt but sync_android_to_sdcard.sh
# hasn't run yet, $SD still holds the OLD bytes. Baking against stale bytes
# here would silently mismatch the odex against the newer APK that eventually
# lands on the card, and Dalvik's side-by-side dependency check (sourceAvail=
# false) does not catch this since it skips modWhen/CRC of the APK itself.
[ -f "$OVERLAY/system/app/$APK_NAME.apk" ] || {
    echo "missing $OVERLAY/system/app/$APK_NAME.apk -- run build_launcher.sh first"; exit 1; }
mkdir -p "$FAKEROOT/system/app"
cp -v "$OVERLAY/system/app/$APK_NAME.apk" "$FAKEROOT/system/app/$APK_NAME.apk"
cp "$BUILD/dexopt/dexopt_qemu" "$FAKEROOT/system/bin/dexopt"
chmod 755 "$FAKEROOT/system/bin/dexopt"
cp "$QEMU" "$FAKEROOT/qemu-arm-static"

echo "=== 2. binfmt_misc qemu-arm (dexopt itself never execs, but be safe) ==="
if [ ! -e /proc/sys/fs/binfmt_misc/qemu-arm ]; then
    REGFILE=$(mktemp)
    printf ':qemu-arm:M::\\x7fELF\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x28\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:%s:F\n' "$QEMU" > "$REGFILE"
    a3ds_sudo bash -c "cat '$REGFILE' > /proc/sys/fs/binfmt_misc/register"
    rm -f "$REGFILE"
fi

echo "=== 3. run dexopt --zip under qemu in a private mount namespace ==="
# --zip mode takes fds, not paths: 3=selected APK (O_RDONLY), 4=output
# (O_RDWR, freshly truncated). dexopt inherits them through qemu, which maps
# guest fds 1:1 to host fds. Flags empty string = installd's default when
# dalvik.vm.dexopt-flags is unset (verify all, opt verified).
RUNSCRIPT="$FAKEROOT/run_${APK_NAME}_preopt.sh"
cat > "$RUNSCRIPT" <<EOF
#!/bin/bash
set -e
mkdir -p /system /data
mount --bind "$FAKEROOT/system" /system
mount --bind "$FAKEROOT/data" /data
export ANDROID_ROOT=/system
export ANDROID_DATA=/data
export BOOTCLASSPATH=/system/framework/core.jar:/system/framework/framework.jar:/system/framework/services.jar
rm -f /system/app/$APK_NAME.odex
: > /system/app/$APK_NAME.odex
exec 3< /system/app/$APK_NAME.apk
exec 4<> /system/app/$APK_NAME.odex
"$QEMU" "$BUILD/dexopt/dexopt_qemu" --zip 3 4 /system/app/$APK_NAME.apk ""
rc=\$?
exec 3<&- 4<&-
exit \$rc
EOF
chmod 755 "$RUNSCRIPT"
a3ds_sudo unshare --mount -- "$RUNSCRIPT"
a3ds_sudo chown "$(id -u)":"$(id -g)" "$FAKEROOT/system/app/$APK_NAME.odex" 2>/dev/null || true

echo "=== 4. result ==="
ls -la "$FAKEROOT/system/app/$APK_NAME.odex"
head -c 8 "$FAKEROOT/system/app/$APK_NAME.odex" | od -c | head -1

echo "=== 5. deploy to SD staging /system/app/ ==="
mkdir -p "$SD/system/app"
cp -v "$FAKEROOT/system/app/$APK_NAME.odex" "$SD/system/app/$APK_NAME.odex"
chmod 644 "$SD/system/app/$APK_NAME.odex"

echo "=== 6. deploy to rootfs overlay (source of truth) ==="
# sync_android_to_sdcard.sh rsyncs --delete "$SRC/system/" over "$SD/system/"
# and refreshes output/target from the overlay first. Launcher2.apk ships in
# the overlay (build_launcher.sh), so the odex must live there too or the next
# sync deletes it from the card.
mkdir -p "$OVERLAY/system/app"
cp -v "$FAKEROOT/system/app/$APK_NAME.odex" "$OVERLAY/system/app/$APK_NAME.odex"
chmod 644 "$OVERLAY/system/app/$APK_NAME.odex"

mkdir -p "$WSL_SD/system/app"
cp -v "$FAKEROOT/system/app/$APK_NAME.odex" "$WSL_SD/system/app/$APK_NAME.odex"
chmod 644 "$WSL_SD/system/app/$APK_NAME.odex"
# N3DS_PIN_MTIME_PARITY: the two cp calls above run milliseconds apart, and the
# Windows-copy release gate compares the staging trees with rsync -t (whole
# seconds). Whenever the copies straddle a second boundary the gate fails on
# mtime alone (.f..t...... app/MicTest.odex, 2026-09-30). Mirror the mtime.
touch -r "$SD/system/app/$APK_NAME.odex" "$WSL_SD/system/app/$APK_NAME.odex"

echo "=== done ==="
ls -la "$SD/system/app/" "$OVERLAY/system/app/"
